---
title: "Poročilo pri predmetu Analiza podatkov s programom R-Analiza štipendiranja v Sloveniji"
author: "Mojca Žilavec"
output:
  pdf_document:
    latex_engine: xelatex
    includes:
      in_header: lib/styles.sty
---

```{r setup, echo=FALSE, results='hide', message=FALSE}
# Če želimo nastaviti pisave v PDF-ju, odkomentiramo
# in sledimo navodilom v programu.
#source("fontconfig.r", encoding = "UTF-8")

# Uvoz vseh potrebnih knjižnic
source("lib/libraries.r", encoding = "UTF-8")
```

# Izbira teme

Za vzorec bomo prikazali nekaj podatkov o slovenskih občinah.

***

# Obdelava, uvoz in čiščenje podatkov

```{r uvoz, echo=FALSE,message=FALSE, warning=FALSE}
source("uvoz/uvoz.r", encoding = "UTF-8")
```

Uvozili smo podatke o občinah v obliki CSV s statističnega urada ter v obliki HTML
z Wikipedije. Poglejmo si začetka obeh uvoženih razpredelnic.


Slika \ref{fig:histogram} prikazuje porazdelitev števila naselij v občinah.

```{r histogram, echo=FALSE, fig.align='center', fig.cap='Histogram števila naselij v občinah'}
#hist(obcine[,4], main = "Pogostost števila naselij",
#     xlab = "Število naselij", ylab = "Število občin")
```

***
